from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class BrowserBridge(Protocol):
    """Protocol defining the browser bridge interface used by executors."""

    async def goto(self, url: str) -> dict: ...
    async def reset_ref_map(self) -> None: ...
    async def click(self, selector: str, click_count: int = 1) -> dict: ...
    async def fill(self, selector: str, text: str) -> dict: ...
    async def a11y_snapshot(self) -> dict: ...
    async def _progressive_snapshot(self, query: str = "") -> dict: ...
    async def simplify_dom(self, query: str = "", in_viewport: bool = False) -> dict: ...
    async def simplified_snapshot(self) -> dict: ...
    async def capture_snapshot(self) -> dict: ...
    async def evaluate(self, js: str) -> Any: ...
    async def get_page_html(self, cached: bool = False) -> str: ...
    async def source(self) -> str: ...
    async def expand_branch(self, key: str, limit: int = 30, offset: int = 0) -> dict: ...
    def get_element_by_index(self, ref: str) -> dict: ...  # sync
    async def hover(self, selector: str) -> dict: ...
    async def unhover(self, selector: str) -> dict: ...
    async def focus(self, selector: str) -> dict: ...
    async def select(self, selector: str, value: str, mode: str = "value") -> dict: ...
    async def clear(self, selector: str, mode: str = "js") -> dict: ...
    async def keyboard_press(self, key: str) -> dict: ...
    async def keyboard_type(self, text: str) -> dict: ...
    async def navigate(self, action: str, hard: bool = False) -> dict: ...
    async def wait(self, mode: str = "time", **kwargs: Any) -> dict: ...
    async def tab_new(self, url: str = "about:blank") -> dict: ...
    async def tab_switch(self, target_id: str) -> dict: ...
    async def tab_close(self, target_id: str) -> dict: ...
    async def tab_list(self) -> list[dict]: ...
    async def copy_to_clipboard(self, selector: str) -> dict: ...
    async def paste_from_clipboard(self, selector: str, index: int = -1) -> dict: ...
    async def ensure_highlights(self, page: Any = None) -> None: ...
    async def wait_for_network_idle(self) -> None: ...
    @property
    def page(self) -> Any: ...
